'''
overall settings 
'''
from colorama import Fore, Back, Style


BUFFER_RIGHT = 10
BUFFER_DOWN = 10

BG_COLOR = Back.BLUE
BG_ACCENT_COLOR = Back.BLACK
ACCENT_AMT = 0.01
GND_COLOR = Back.MAGENTA
SKY_COLOR = Back.MAGENTA

GAME_SPEED = 1.5
BALL_SPEED = 2

GND_HEIGHT = 3
SKY_DEPTH = 3

MAX_LIVES = 3

FG_DEPTH = 3
DESIGN_BASE_PATH = 'art'
KEY_FORCE = 2.5
GRAVITY_X = 0.26
PADDLE_START_Y = 40
BOTTOM_HEIGHT = 3
TOP_DEPTH = 3